### ISSUE TITLE
Doesn't work with script defer

### ISSUE THREAD

**Issue by jayhasgin** [BetaHuhn/feedback-js#69]

**Comment by BetaHuhn** [comment]
What do you mean by doesn't work? Is it not loading the script or is the button not showing up?

Could you share the script tag and the options you are passing it?

**Comment by jayhasgin** [comment]
I meant it doesn't load, show the button. I was using <script defer src="..." data-feedback-opts='{"endpoint": "..." }...'></script>

Maybe the load eventlistener in line 21 in index.js never triggers because the event had already happened?! Now I use a little hack skipping that event listener and also manually calling window.feedback.renderButton(); in global scope, but this would only work with defer.

**Comment by BetaHuhn** [comment]
It works for me with `defer`, the example on [Codepen](https://codepen.io/BetaHuhn/pen/MWebeXp) also seems to work fine with `defer`.

One issue that might be related is that we are waiting for the `load` event ([L21](https://github.com/BetaHuhn/feedback-js/blob/8ebe8ef0c68c6ed5ba6719cf56817896dda7dc4a/src/index.js#L21)). If your page loads a lot of content like images it might take a while for the event to fire. We could change it to `DOMContentLoaded`.

I changed this on the [develop](https://github.com/BetaHuhn/feedback-js/commits/develop) branch yesterday, you could try if it works by using `https://cdn.jsdelivr.net/gh/betahuhn/feedback-js@develop/dist/feedback-js.min.js` as the script src.

**Comment by jayhasgin** [comment]
It works now. Must've been the CSP issue not executing any script, and may had nothing to do with defer. I've added PR for CSP fix.
